-- Migration unit 1: schema_changes
-- Transaction mode: transactional
-- Boundary reason: default

SET check_function_bodies = false;

DROP EXTENSION pg_net;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM anon;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM authenticated;

ALTER DEFAULT PRIVILEGES FOR ROLE postgres IN SCHEMA public REVOKE UPDATE ON SEQUENCES FROM service_role;

CREATE TYPE public.list_role AS ENUM (
  'owner',
  'editor',
  'viewer'
);

CREATE TYPE public.list_type AS ENUM (
  'wishlist',
  'reading',
  'custom'
);

CREATE TYPE public.list_visibility AS ENUM (
  'private',
  'shared',
  'public'
);

CREATE TYPE public.relationship_type AS ENUM (
  'required_before',
  'recommended_before',
  'tie_in',
  'concurrent',
  'inspired_by',
  'continuation',
  'alternate_take'
);

CREATE TYPE public.run_status AS ENUM (
  'draft',
  'verified'
);

CREATE TYPE public.run_type AS ENUM (
  'creative_run',
  'event',
  'reading_order',
  'era'
);

CREATE FUNCTION public.handle_new_user()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  SECURITY DEFINER
  AS $function$begin
    insert into public.profiles (
        id,
        username,
        display_name
    )
    values (
        new.id,
        new.raw_user_meta_data->>'username',
        new.raw_user_meta_data->>'username'
    );

    return new;
end;$function$;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION public.handle_new_user();

CREATE FUNCTION public.increment_app_counter (
  counter_key text
)
  RETURNS bigint
  LANGUAGE sql
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  insert into app_counters (key, value)
  values (counter_key, 1)
  on conflict (key) do update set value = app_counters.value + 1
  returning value;
$function$;

GRANT ALL ON FUNCTION public.increment_app_counter(text) TO authenticated;

CREATE FUNCTION public.is_list_member (
  p_list_id uuid,
  p_user_id uuid
)
  RETURNS boolean
  LANGUAGE sql
  STABLE
  SECURITY DEFINER
  SET search_path TO 'public'
  AS $function$
  select exists (
    select 1 from list_members
    where list_id = p_list_id and user_id = p_user_id
  );
$function$;

CREATE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE TABLE public.app_counters (
  key   text   NOT NULL,
  value bigint DEFAULT 0 NOT NULL
);

ALTER TABLE public.app_counters
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.app_counters
  ADD CONSTRAINT app_counters_pkey PRIMARY KEY (key);

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.app_counters TO anon;

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON public.app_counters TO authenticated;

GRANT MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON public.app_counters TO service_role;

CREATE TABLE public.barcode_lookups (
  upc        text                     NOT NULL,
  issue_id   uuid                     NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.barcode_lookups
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.barcode_lookups
  ADD CONSTRAINT barcode_lookups_pkey PRIMARY KEY (upc);

GRANT ALL ON public.barcode_lookups TO anon;

GRANT ALL ON public.barcode_lookups TO authenticated;

GRANT ALL ON public.barcode_lookups TO service_role;

CREATE POLICY barcode_lookups_insert_authenticated ON public.barcode_lookups
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY barcode_lookups_select_authenticated ON public.barcode_lookups
  FOR SELECT
  TO authenticated
  USING (true);

CREATE TABLE public.covers (
  id         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  image_hash text,
  issue_id   uuid                     DEFAULT gen_random_uuid()
);

ALTER TABLE public.covers
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.covers
  ADD CONSTRAINT covers_issue_id_key UNIQUE (issue_id);

ALTER TABLE public.covers
  ADD CONSTRAINT covers_pkey PRIMARY KEY (id);

GRANT ALL ON public.covers TO anon;

GRANT ALL ON public.covers TO authenticated;

GRANT ALL ON public.covers TO service_role;

CREATE POLICY "Enable read access for all users" ON public.covers
  FOR SELECT
  USING (true);

CREATE TABLE public.creators (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  first_name        text,
  last_name         text,
  created_at        timestamp with time zone DEFAULT now(),
  comicvine_id      bigint,
  api_source        text                     DEFAULT 'comicvine'::text NOT NULL,
  synced_at         timestamp with time zone DEFAULT now(),
  external_metadata jsonb
);

ALTER TABLE public.creators
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.creators
  ADD CONSTRAINT creators_comicvine_id_key UNIQUE (comicvine_id);

ALTER TABLE public.creators
  ADD CONSTRAINT creators_pkey PRIMARY KEY (id);

GRANT ALL ON public.creators TO anon;

GRANT ALL ON public.creators TO authenticated;

GRANT ALL ON public.creators TO service_role;

CREATE POLICY "Enable read access for all users" ON public.creators
  FOR SELECT
  USING (true);

CREATE TABLE public.favorite_creators (
  user_id    uuid                     NOT NULL,
  creator_id uuid                     NOT NULL,
  added_at   timestamp with time zone DEFAULT now()
);

ALTER TABLE public.favorite_creators
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.favorite_creators
  ADD CONSTRAINT favorite_creators_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.creators(id) ON DELETE CASCADE;

ALTER TABLE public.favorite_creators
  ADD CONSTRAINT favorite_creators_pkey PRIMARY KEY (user_id, creator_id);

ALTER TABLE public.favorite_creators
  ADD CONSTRAINT favorite_creators_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

GRANT ALL ON public.favorite_creators TO anon;

GRANT ALL ON public.favorite_creators TO authenticated;

GRANT ALL ON public.favorite_creators TO service_role;

CREATE POLICY "Users can favorite creators" ON public.favorite_creators
  FOR INSERT
  TO authenticated
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can unfavorite creators" ON public.favorite_creators
  FOR DELETE
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view favorite creators" ON public.favorite_creators
  FOR SELECT
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE TABLE public.favorite_publishers (
  user_id      uuid                     NOT NULL,
  publisher_id uuid                     NOT NULL,
  added_at     timestamp with time zone DEFAULT now()
);

ALTER TABLE public.favorite_publishers
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.favorite_publishers
  ADD CONSTRAINT favorite_publishers_pkey PRIMARY KEY (user_id, publisher_id);

ALTER TABLE public.favorite_publishers
  ADD CONSTRAINT favorite_publishers_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

GRANT ALL ON public.favorite_publishers TO anon;

GRANT ALL ON public.favorite_publishers TO authenticated;

GRANT ALL ON public.favorite_publishers TO service_role;

CREATE POLICY "Users can favorite publishers" ON public.favorite_publishers
  FOR INSERT
  TO authenticated
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can unfavorite publishers" ON public.favorite_publishers
  FOR DELETE
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view favorite publishers" ON public.favorite_publishers
  FOR SELECT
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE TABLE public.favorite_runs (
  user_id  uuid                     NOT NULL,
  run_id   uuid                     NOT NULL,
  added_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.favorite_runs
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.favorite_runs
  ADD CONSTRAINT favorite_runs_pkey PRIMARY KEY (user_id, run_id);

ALTER TABLE public.favorite_runs
  ADD CONSTRAINT favorite_runs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

GRANT ALL ON public.favorite_runs TO anon;

GRANT ALL ON public.favorite_runs TO authenticated;

GRANT ALL ON public.favorite_runs TO service_role;

CREATE POLICY "Users can favorite runs" ON public.favorite_runs
  FOR INSERT
  TO authenticated
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can unfavorite runs" ON public.favorite_runs
  FOR DELETE
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view favorite runs" ON public.favorite_runs
  FOR SELECT
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE TABLE public.favorite_series (
  user_id   uuid                     NOT NULL,
  series_id uuid                     NOT NULL,
  added_at  timestamp with time zone DEFAULT now()
);

ALTER TABLE public.favorite_series
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.favorite_series
  ADD CONSTRAINT favorite_series_pkey PRIMARY KEY (user_id, series_id);

ALTER TABLE public.favorite_series
  ADD CONSTRAINT favorite_series_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

GRANT ALL ON public.favorite_series TO anon;

GRANT ALL ON public.favorite_series TO authenticated;

GRANT ALL ON public.favorite_series TO service_role;

CREATE POLICY "Users can favorite series" ON public.favorite_series
  FOR INSERT
  TO authenticated
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can unfavorite series" ON public.favorite_series
  FOR DELETE
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can view favorite series" ON public.favorite_series
  FOR SELECT
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE TABLE public.issue_creators (
  issue_id   uuid NOT NULL,
  creator_id uuid NOT NULL,
  role       text NOT NULL
);

ALTER TABLE public.issue_creators
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.issue_creators
  ADD CONSTRAINT issue_creators_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.creators(id) ON DELETE CASCADE;

ALTER TABLE public.issue_creators
  ADD CONSTRAINT issue_creators_pkey PRIMARY KEY (issue_id, creator_id, ROLE);

GRANT ALL ON public.issue_creators TO anon;

GRANT ALL ON public.issue_creators TO authenticated;

GRANT ALL ON public.issue_creators TO service_role;

CREATE POLICY "Enable read access for all users" ON public.issue_creators
  FOR SELECT
  USING (true);

CREATE TABLE public.issues (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  title             text                     NOT NULL,
  issue_number      text,
  release_date      date,
  cover_url         text,
  created_at        timestamp with time zone DEFAULT now(),
  volume_id         uuid,
  comicvine_id      bigint,
  api_source        text                     DEFAULT 'comicvine'::text,
  synced_at         timestamp with time zone DEFAULT now(),
  external_metadata jsonb,
  sort_number       numeric
);

ALTER TABLE public.issues
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.issues
  ADD CONSTRAINT issues_comicvine_id_key UNIQUE (comicvine_id);

ALTER TABLE public.issues
  ADD CONSTRAINT issues_pkey PRIMARY KEY (id);

ALTER TABLE public.barcode_lookups
  ADD CONSTRAINT barcode_lookups_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;

ALTER TABLE public.covers
  ADD CONSTRAINT covers_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON UPDATE CASCADE;

ALTER TABLE public.issue_creators
  ADD CONSTRAINT issue_creators_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;

GRANT ALL ON public.issues TO anon;

GRANT ALL ON public.issues TO authenticated;

GRANT ALL ON public.issues TO service_role;

CREATE INDEX issues_volume_id_idx ON public.issues (volume_id);

CREATE POLICY "Enable read access for all users" ON public.issues
  FOR SELECT
  USING (true);

CREATE TABLE public.list_items (
  list_id  uuid                     NOT NULL,
  issue_id uuid                     NOT NULL,
  added_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.list_items
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.list_items
  ADD CONSTRAINT list_items_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;

ALTER TABLE public.list_items
  ADD CONSTRAINT list_items_pkey PRIMARY KEY (list_id, issue_id);

GRANT ALL ON public.list_items TO anon;

GRANT ALL ON public.list_items TO authenticated;

GRANT ALL ON public.list_items TO service_role;

CREATE TABLE public.list_members (
  list_id   uuid                     NOT NULL,
  user_id   uuid                     NOT NULL,
  role      public.list_role         NOT NULL,
  joined_at timestamp with time zone DEFAULT now()
);

ALTER TABLE public.list_members
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.list_members
  ADD CONSTRAINT list_members_pkey PRIMARY KEY (list_id, user_id);

ALTER TABLE public.list_members
  ADD CONSTRAINT list_members_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

GRANT ALL ON public.list_members TO anon;

GRANT ALL ON public.list_members TO authenticated;

GRANT ALL ON public.list_members TO service_role;

CREATE TABLE public.lists (
  id          uuid                     DEFAULT gen_random_uuid() NOT NULL,
  owner_id    uuid                     NOT NULL,
  name        text                     NOT NULL,
  type        public.list_type         DEFAULT 'custom'::public.list_type NOT NULL,
  visibility  public.list_visibility   DEFAULT 'private'::public.list_visibility NOT NULL,
  description text,
  created_at  timestamp with time zone DEFAULT now()
);

CREATE POLICY "Members can add list items" ON public.list_items
  FOR INSERT
  TO authenticated
  WITH CHECK (((EXISTS ( SELECT 1
   FROM public.lists
  WHERE ((lists.id = list_items.list_id) AND (lists.owner_id = auth.uid())))) OR (EXISTS ( SELECT 1
   FROM public.list_members
  WHERE
    ((list_members.list_id = list_items.list_id) AND (list_members.user_id = auth.uid()) AND (list_members.role = ANY (ARRAY['owner'::public.list_role,
    'editor'::public.list_role])))))));

CREATE POLICY "Owners can remove list items" ON public.list_items
  FOR DELETE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM public.lists
  WHERE ((lists.id = list_items.list_id) AND (lists.owner_id = auth.uid())))));

CREATE POLICY "Users can view list items" ON public.list_items
  FOR SELECT
  USING ((EXISTS ( SELECT 1
   FROM public.lists
  WHERE
    ((lists.id = list_items.list_id) AND ((lists.visibility = 'public'::public.list_visibility) OR (lists.owner_id = auth.uid()) OR public.is_list_member(lists.id, auth.uid()))))));

CREATE POLICY "Owners can add members" ON public.list_members
  FOR INSERT
  TO authenticated
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.lists
  WHERE ((lists.id = list_members.list_id) AND (lists.owner_id = auth.uid())))));

CREATE POLICY "Owners can update members" ON public.list_members
  FOR UPDATE
  TO authenticated
  USING ((EXISTS ( SELECT 1
   FROM public.lists
  WHERE ((lists.id = list_members.list_id) AND (lists.owner_id = auth.uid())))))
  WITH CHECK ((EXISTS ( SELECT 1
   FROM public.lists
  WHERE ((lists.id = list_members.list_id) AND (lists.owner_id = auth.uid())))));

CREATE POLICY "Owners or users can remove members" ON public.list_members
  FOR DELETE
  TO authenticated
  USING (((user_id = auth.uid()) OR (EXISTS ( SELECT 1
   FROM public.lists
  WHERE ((lists.id = list_members.list_id) AND (lists.owner_id = auth.uid()))))));

CREATE POLICY "Users can view list members" ON public.list_members
  FOR SELECT
  TO authenticated
  USING ((public.is_list_member(list_id, auth.uid()) OR (EXISTS ( SELECT 1
   FROM public.lists
  WHERE ((lists.id = list_members.list_id) AND (lists.owner_id = auth.uid()))))));

ALTER TABLE public.lists
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.lists
  ADD CONSTRAINT lists_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.lists
  ADD CONSTRAINT lists_pkey PRIMARY KEY (id);

ALTER TABLE public.list_items
  ADD CONSTRAINT list_items_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.lists(id) ON DELETE CASCADE;

ALTER TABLE public.list_members
  ADD CONSTRAINT list_members_list_id_fkey FOREIGN KEY (list_id) REFERENCES public.lists(id) ON DELETE CASCADE;

GRANT ALL ON public.lists TO anon;

GRANT ALL ON public.lists TO authenticated;

GRANT ALL ON public.lists TO service_role;

CREATE POLICY "Owners can delete lists" ON public.lists
  FOR DELETE
  TO authenticated
  USING ((auth.uid() = owner_id));

CREATE POLICY "Owners can update lists" ON public.lists
  FOR UPDATE
  TO authenticated
  USING ((auth.uid() = owner_id))
  WITH CHECK ((auth.uid() = owner_id));

CREATE POLICY "Users can create lists" ON public.lists
  FOR INSERT
  TO authenticated
  WITH CHECK ((auth.uid() = owner_id));

CREATE POLICY "Users can view accessible lists" ON public.lists
  FOR SELECT
  USING (((visibility = 'public'::public.list_visibility) OR (owner_id = auth.uid()) OR public.is_list_member(id, auth.uid())));

CREATE TABLE public.profiles (
  id           uuid                     NOT NULL,
  username     text,
  display_name text,
  avatar_url   text,
  bio          text,
  created_at   timestamp with time zone DEFAULT now(),
  updated_at   timestamp with time zone DEFAULT now()
);

ALTER TABLE public.profiles
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_pkey PRIMARY KEY (id);

ALTER TABLE public.profiles
  ADD CONSTRAINT profiles_username_key UNIQUE (username);

GRANT ALL ON public.profiles TO anon;

GRANT ALL ON public.profiles TO authenticated;

GRANT ALL ON public.profiles TO service_role;

CREATE POLICY "Profiles are publicly readable" ON public.profiles
  FOR SELECT
  USING (true);

CREATE POLICY "Users can update their profile" ON public.profiles
  FOR UPDATE
  TO authenticated
  USING ((auth.uid() = id))
  WITH CHECK ((auth.uid() = id));

CREATE TABLE public.publishers (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  name              text                     NOT NULL,
  website           text,
  logo_url          text,
  created_at        timestamp with time zone DEFAULT now(),
  comicvine_id      bigint,
  api_source        text                     DEFAULT 'comicvine'::text,
  synced_at         timestamp with time zone DEFAULT now(),
  external_metadata jsonb
);

ALTER TABLE public.publishers
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.publishers
  ADD CONSTRAINT publishers_comicvine_id_key UNIQUE (comicvine_id);

ALTER TABLE public.publishers
  ADD CONSTRAINT publishers_name_key UNIQUE (name);

ALTER TABLE public.publishers
  ADD CONSTRAINT publishers_pkey PRIMARY KEY (id);

ALTER TABLE public.favorite_publishers
  ADD CONSTRAINT favorite_publishers_publisher_id_fkey FOREIGN KEY (publisher_id) REFERENCES public.publishers(id) ON DELETE CASCADE;

GRANT ALL ON public.publishers TO anon;

GRANT ALL ON public.publishers TO authenticated;

GRANT ALL ON public.publishers TO service_role;

CREATE POLICY "Enable read access for all users" ON public.publishers
  FOR SELECT
  USING (true);

CREATE TABLE public.run_creators (
  run_id     uuid NOT NULL,
  creator_id uuid NOT NULL,
  role       text NOT NULL
);

ALTER TABLE public.run_creators
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.run_creators
  ADD CONSTRAINT run_creators_creator_id_fkey FOREIGN KEY (creator_id) REFERENCES public.creators(id) ON DELETE CASCADE;

ALTER TABLE public.run_creators
  ADD CONSTRAINT run_creators_pkey PRIMARY KEY (run_id, creator_id, ROLE);

GRANT ALL ON public.run_creators TO anon;

GRANT ALL ON public.run_creators TO authenticated;

GRANT ALL ON public.run_creators TO service_role;

CREATE POLICY "Authenticated users can add run creators" ON public.run_creators
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete run creators" ON public.run_creators
  FOR DELETE
  TO authenticated
  USING (true);

CREATE POLICY "Enable read access for all users" ON public.run_creators
  FOR SELECT
  USING (true);

CREATE TABLE public.run_items (
  run_id     uuid   NOT NULL,
  volume_id  uuid,
  issue_id   uuid,
  "position" bigint NOT NULL,
  id         uuid   DEFAULT gen_random_uuid() NOT NULL
);

ALTER TABLE public.run_items
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.run_items
  ADD CONSTRAINT run_items_exactly_one CHECK ((issue_id IS NOT NULL) <> (volume_id IS NOT NULL));

ALTER TABLE public.run_items
  ADD CONSTRAINT run_items_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON UPDATE CASCADE;

ALTER TABLE public.run_items
  ADD CONSTRAINT run_items_not_empty CHECK (issue_id IS NOT NULL OR volume_id IS NOT NULL);

ALTER TABLE public.run_items
  ADD CONSTRAINT run_items_pkey PRIMARY KEY (id);

ALTER TABLE public.run_items
  ADD CONSTRAINT run_items_run_position_unique UNIQUE (run_id, "position");

GRANT ALL ON public.run_items TO anon;

GRANT ALL ON public.run_items TO authenticated;

GRANT ALL ON public.run_items TO service_role;

CREATE INDEX idx_run_items_run ON public.run_items (run_id);

CREATE INDEX idx_run_items_volume ON public.run_items (volume_id);

CREATE INDEX idx_run_items_issue ON public.run_items (issue_id);

CREATE POLICY "Anyone can view run volumes" ON public.run_items
  FOR SELECT
  USING (true);

CREATE POLICY "Authenticated users can add run items" ON public.run_items
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete run items" ON public.run_items
  FOR DELETE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can update run items" ON public.run_items
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE TABLE public.run_relationships (
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  source_run_id uuid                     NOT NULL,
  target_run_id uuid                     NOT NULL,
  relationship  public.relationship_type NOT NULL,
  created_at    timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.run_relationships
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.run_relationships
  ADD CONSTRAINT no_self_relationship CHECK (source_run_id <> target_run_id);

ALTER TABLE public.run_relationships
  ADD CONSTRAINT run_relationships_pkey PRIMARY KEY (id);

ALTER TABLE public.run_relationships
  ADD CONSTRAINT unique_relationship UNIQUE (source_run_id, target_run_id, relationship);

GRANT ALL ON public.run_relationships TO anon;

GRANT ALL ON public.run_relationships TO authenticated;

GRANT ALL ON public.run_relationships TO service_role;

CREATE INDEX idx_run_relationships_source ON public.run_relationships (source_run_id);

CREATE INDEX idx_run_relationships_target ON public.run_relationships (target_run_id);

CREATE POLICY "Authenticated users can add run relationships" ON public.run_relationships
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete run relationships" ON public.run_relationships
  FOR DELETE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can update run relationships" ON public.run_relationships
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.run_relationships
  FOR SELECT
  USING (true);

CREATE TABLE public.runs (
  id          uuid                     DEFAULT gen_random_uuid() NOT NULL,
  name        text                     NOT NULL,
  start_year  integer,
  end_year    integer,
  created_at  timestamp with time zone DEFAULT now(),
  type        public.run_type          DEFAULT 'creative_run'::public.run_type,
  status      public.run_status        DEFAULT 'draft'::public.run_status NOT NULL,
  verified_at timestamp with time zone,
  description text,
  confidence  numeric(3,2)             DEFAULT 0.00
);

COMMENT ON TABLE public.runs IS 'A run is a curated reading experience consisting of ordered issues, volumes, or series that belong together.';

ALTER TABLE public.runs
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.runs
  ADD CONSTRAINT runs_pkey PRIMARY KEY (id);

ALTER TABLE public.favorite_runs
  ADD CONSTRAINT favorite_runs_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;

ALTER TABLE public.run_creators
  ADD CONSTRAINT run_creators_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;

ALTER TABLE public.run_items
  ADD CONSTRAINT run_volumes_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.runs(id) ON DELETE CASCADE;

ALTER TABLE public.run_relationships
  ADD CONSTRAINT fk_source_run FOREIGN KEY (source_run_id) REFERENCES public.runs(id) ON DELETE CASCADE;

ALTER TABLE public.run_relationships
  ADD CONSTRAINT fk_target_run FOREIGN KEY (target_run_id) REFERENCES public.runs(id) ON DELETE CASCADE;

GRANT ALL ON public.runs TO anon;

GRANT ALL ON public.runs TO authenticated;

GRANT ALL ON public.runs TO service_role;

CREATE POLICY "Authenticated users can create runs" ON public.runs
  FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated users can delete runs" ON public.runs
  FOR DELETE
  TO authenticated
  USING (true);

CREATE POLICY "Authenticated users can update runs" ON public.runs
  FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Enable read access for all users" ON public.runs
  FOR SELECT
  USING (true);

CREATE TABLE public.series (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  publisher_id      uuid                     NOT NULL,
  name              text                     NOT NULL,
  created_at        timestamp with time zone DEFAULT now(),
  comicvine_id      bigint,
  api_source        text                     DEFAULT 'comicvine'::text,
  synced_at         timestamp with time zone DEFAULT now(),
  external_metadata jsonb,
  slug              text,
  normalized_name   text
);

ALTER TABLE public.series
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.series
  ADD CONSTRAINT series_comicvine_id_key UNIQUE (comicvine_id);

ALTER TABLE public.series
  ADD CONSTRAINT series_pkey PRIMARY KEY (id);

ALTER TABLE public.favorite_series
  ADD CONSTRAINT favorite_series_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id) ON DELETE CASCADE;

ALTER TABLE public.series
  ADD CONSTRAINT series_publisher_id_fkey FOREIGN KEY (publisher_id) REFERENCES public.publishers(id) ON DELETE RESTRICT;

ALTER TABLE public.series
  ADD CONSTRAINT series_slug_key UNIQUE (slug);

GRANT ALL ON public.series TO anon;

GRANT ALL ON public.series TO authenticated;

GRANT ALL ON public.series TO service_role;

CREATE POLICY "Enable read access for all users" ON public.series
  FOR SELECT
  USING (true);

CREATE TABLE public.user_comics (
  id            uuid                     DEFAULT gen_random_uuid() NOT NULL,
  user_id       uuid                     NOT NULL,
  issue_id      uuid                     NOT NULL,
  owned         boolean                  DEFAULT false,
  read          boolean                  DEFAULT false,
  rating        integer,
  notes         text,
  purchase_date date,
  created_at    timestamp with time zone DEFAULT now()
);

ALTER TABLE public.user_comics
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.user_comics
  ADD CONSTRAINT user_comics_issue_id_fkey FOREIGN KEY (issue_id) REFERENCES public.issues(id) ON DELETE CASCADE;

ALTER TABLE public.user_comics
  ADD CONSTRAINT user_comics_pkey PRIMARY KEY (id);

ALTER TABLE public.user_comics
  ADD CONSTRAINT user_comics_rating_check CHECK (rating >= 1 AND rating <= 10);

ALTER TABLE public.user_comics
  ADD CONSTRAINT user_comics_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE;

ALTER TABLE public.user_comics
  ADD CONSTRAINT user_comics_user_id_issue_id_key UNIQUE (user_id, issue_id);

GRANT ALL ON public.user_comics TO anon;

GRANT ALL ON public.user_comics TO authenticated;

GRANT ALL ON public.user_comics TO service_role;

CREATE POLICY "Users can add comics to their collection" ON public.user_comics
  FOR INSERT
  TO authenticated
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can remove comics from their collection" ON public.user_comics
  FOR DELETE
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE POLICY "Users can update their collection" ON public.user_comics
  FOR UPDATE
  TO authenticated
  USING ((auth.uid() = user_id))
  WITH CHECK ((auth.uid() = user_id));

CREATE POLICY "Users can view their collection" ON public.user_comics
  FOR SELECT
  TO authenticated
  USING ((auth.uid() = user_id));

CREATE TABLE public.volumes (
  id                uuid                     DEFAULT gen_random_uuid() NOT NULL,
  publisher_id      uuid,
  series_id         uuid,
  name              text                     NOT NULL,
  description       text,
  start_year        integer,
  end_year          integer,
  cover_url         text,
  comicvine_id      bigint,
  created_at        timestamp with time zone DEFAULT now(),
  api_source        text                     DEFAULT 'comicvine'::text,
  synced_at         timestamp with time zone DEFAULT now(),
  external_metadata jsonb
);

ALTER TABLE public.volumes
  ENABLE ROW LEVEL SECURITY;

ALTER TABLE public.volumes
  ADD CONSTRAINT volumes_comicvine_id_key UNIQUE (comicvine_id);

ALTER TABLE public.volumes
  ADD CONSTRAINT volumes_pkey PRIMARY KEY (id);

ALTER TABLE public.issues
  ADD CONSTRAINT issues_volume_id_fkey FOREIGN KEY (volume_id) REFERENCES public.volumes(id) ON DELETE CASCADE;

ALTER TABLE public.run_items
  ADD CONSTRAINT run_volumes_volume_id_fkey FOREIGN KEY (volume_id) REFERENCES public.volumes(id) ON DELETE CASCADE;

ALTER TABLE public.volumes
  ADD CONSTRAINT volumes_publisher_id_fkey FOREIGN KEY (publisher_id) REFERENCES public.publishers(id) ON DELETE SET NULL;

ALTER TABLE public.volumes
  ADD CONSTRAINT volumes_series_id_fkey FOREIGN KEY (series_id) REFERENCES public.series(id) ON DELETE SET NULL;

GRANT ALL ON public.volumes TO anon;

GRANT ALL ON public.volumes TO authenticated;

GRANT ALL ON public.volumes TO service_role;

CREATE INDEX volumes_series_id_idx ON public.volumes (series_id);

CREATE INDEX volumes_comicvine_id_idx ON public.volumes (comicvine_id);

CREATE INDEX volumes_publisher_id_idx ON public.volumes (publisher_id);

CREATE POLICY "Anyone can view volumes" ON public.volumes
  FOR SELECT
  USING (true);

CREATE EVENT TRIGGER ensure_rls
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION public.rls_auto_enable();
